'use strict'

const proverb = [
  {
    Number: 1,
    saying:"あばたもえくぼ",
    roman:"abatamoekubo",
    meaning:"好きな人ならどんな欠点もよく見える、長所に見えてしまうこと",
    furigana:"あばたもえくぼ",
  },
  {
    Number: 2,
    saying:"雨降って地固まる",
    roman:"amehuttejikatamaru",
    meaning:"悪いことや嫌なことがあった後に、かえって前よりも状態がよくなること",
    furigana:"あめふってじかたまる",
  },
  {
    Number: 3,
    saying:"案ずるより産むが易し",
    roman:"annzuruyoriumugayasusi",
    meaning:"物事やる前に心配したりするが、実際にやってみると案外簡単になものだということ",
    furigana:"あんずるよりうむがやすし",
  },
  {
    Number: 4,
    saying:"急がば回れ",
    roman:"isogabamaware",
    meaning:"急を要する時には遠回りに思えても、確実な方法をとった方がいいということ",
    furigana:"いそがばまわれ",
  },
  {
    Number: 5,
    saying:"犬も歩けば棒に当たる",
    roman:"inumoarukebabouniataru",
    meaning:"何もしないより何か行動してみれば、思わぬ幸運に巡り合うかもしれないということ",
    furigana:"いぬもあるけばぼうにあたる",
  },
  {
    Number: 6,
    saying:"縁の下の力持ち",
    roman:"ennnositanotikaramoti",
    meaning:"人の目につかないところで、人の為や仕事のために努力する人のこと",
    furigana:"えんのしたのちからもち",
  },
  {
    Number: 7,
    saying:"鬼の目にも涙",
    roman:"oninomenimonamida",
    meaning:"どんなに心の冷たい人でも、時には情け深くなるものだということ",
    furigana:"おにのめにもなみだ",
  },
  {
    Number: 8,
    saying:"蛙の子は蛙",
    roman:"kaerunokohakaeru",
    meaning:"子は結局親に似るものであるということ",
    furigana:"かえるのこはかえる",
  },
  {
    Number: 9,
    saying:"果報は寝て待て",
    roman:"kahouhanetemate",
    meaning:"焦らさずじっと待っていれば、そのうちチャンスが巡ってくるということ",
    furigana:"かほうはねてまて",
  },
  {
    Number: 10,
    saying:"楽あれば苦あり",
    roman:"rakuarebakuari",
    meaning:"楽しいこともあれば苦しいこともある",
    furigana:"らくあればくあり",
  },
  {
    Number: 11,
    saying:"芸は身を助ける",
    roman:"geihamiwotasukeru",
    meaning:"趣味で身に着けたことや何か一つの特技が、困ったときに意外に役立ってしまうということ",
    furigana:"げいはみをたすける",
  },
  {
    Number: 12,
    saying:"五十歩百歩",
    roman:"gojyuppohyappo",
    meaning:"すごく違うように見えるが、ほんとはあまり違わないこと",
    furigana:"ごじゅっぽひゃっぽ",
  },
  {
    Number: 13,
    saying:"親しき中にも礼儀あり",
    roman:"sitasikinakanimoreigiari",
    meaning:"親しいからと言って失礼なことを言うと、関係が悪くなってしまうことがある為、気を付けなければならないということ",
    furigana:"したしきなかにもれいぎあり",
  },
  {
    Number: 14,
    saying:"失敗は成功のもと",
    roman:"sippaihaseikounomoto",
    meaning:"失敗してもなぜ失敗したか反省して改めれば、次の成功につながるということ",
    furigana:"しっぱいはせいこうのもと",
  },
  {
    Number: 15,
    saying:"他山の石",
    roman:"tazannnoisi",
    meaning:"他人の誤った言葉や行いでも、自分を磨く糧になるということ",
    furigana:"たざんのいし",
  },
  {
    Number: 16,
    saying:"七転び八起き",
    roman:"nanakorobiyaoki",
    meaning:"何度失敗してもまた立ち上がって挑戦し続けること",
    furigana:"ななころびやおき",
  },
  {
    Number: 17,
    saying:"下手の横好き",
    roman:"hetanoyokozuki",
    meaning:"下手なくせにそのことが大好きで熱心であること",
    furigana:"へたのよこずき",
  },
  {
    Number: 18,
    saying:"三つ子の魂百まで",
    roman:"mitugonotamasiihyakumade",
    meaning:"小さいうちの習慣や性質は、大人になっても変わらないこと",
    furigana:"みつごのたましいひゃくまで",
  },
  {
    Number: 19,
    saying:"論より証拠",
    roman:"ronnyorisyouko",
    meaning:"物事をはっきりさせるためには、議論するよりも証拠を出した方がよいということ",
    furigana:"ろんよりしょうこ",
  },
  {
    Number: 20,
    saying:"笑う門には福来る",
    roman:"waraukadonihahukukitaru",
    meaning:"いつもニコニコと笑っている人には、自然と幸福がやってくるということ",
    furigana:"わらうかどにはふくきたる",
  },
];